version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  services:
    external: true

volumes:
  redis_data:
